### ISSUE TITLE
Failed to resolve artifact with 2.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by jDramaix** [gwt-maven-plugin/gwt-maven-plugin#102]
I'm not sure that the problem is directly linked to the maven plugin, but I receive this error toady when I try to compile my project. 

```
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0-SNAPSHOT:compile (default) on project app: Failed to resolve artifact: Some problems were encountered while processing the POMs:
[ERROR] [FATAL] Non-resolvable parent POM: Could not find artifact org.ow2:ow2:pom:1.3 @ org.ow2.asm:asm-parent:5.0.3, /Users/julien/.m2/repository/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom, line 36, column 11
```

**Comment by preethamjayanna** [comment]
Hi,

I have updated to latest version of maven. Still I get same error. Please guide.

Thanks.
P

**Comment by branflake2267** [comment]
what is the maven version `mvn -v`?

**Comment by preethamjayanna** [comment]
Hi,

Below has the maven version details,

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T02:28:10+05:30)
Maven home: F:\apache-maven-3.2.5\bin\..
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.8.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"

I also tried with maven 3.3.3, but same error

I m using sprint framework. I understand this issue might be due to asm mismatch. My .m2 (repository) folder contains so many version of asm

3.1
3.2
3.3.1

I m using java version "1.8.0_45"

Help in this regard is highly appreciated. I m trying to upgrade to gwt 2.7 from many days and i m stuck with this error.

Thanks,
P

**Comment by SimyungYang** [comment]
Even though I am using the latest version of maven.
i encountered same problem.

> mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T20:57:37+09:00)
Maven home: /Users/simon/dev/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: ko_KR, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"

**Comment by preethamcka** [comment]
Hi,

I had a same problem and it was resolved by ASM version.

I had issue mainly with older version of ASM and I had difficulty in finding which plugin is downloading the older version of ASM, then I figured it out by using maven --debug mode option, which gives the complete log of which plugin was downloading the older version of ASM. Then, I upgraded those plugin's, then it downloaded new version of ASM and it resolved my issue.

Hope it helps

Thanks,
Preetham.J
