### ISSUE TITLE
generateAsync goal fails if wildcard imports used

### ISSUE THREAD

**Issue by lukelast** [gwt-maven-plugin/gwt-maven-plugin#125]
The GWT RPC async interface code generator will fail if your `RemoteService` interface has any wildcard imports.

The workaround is to avoid using wildcards in imports, or avoid using import statements.

**Comment by ibaca** [comment]
Closed because cannot be reproduced (I changed various it cases to use wildcards imports but all of them success).

**Comment by lukelast** [comment]
Thanks for testing it. I am still able to reproduce and I just noticed the types being wildcard imported must be used in the method signature to cause problems. Like this example:

```java
// This wildcard import will not cause problems.
import com.google.gwt.user.client.rpc.*;
// Package contains MyType class.
import com.example.*;

@RemoteServiceRelativePath( "..." )
public interface GwtRpcService extends RemoteService {
   MyType getExample();
}
```

The compiler error should be something like:  "... cannot find symbol symbol:   class MyType"

**Comment by ibaca** [comment]
Can you modify the IT case async-with-inner-class so it fails? thanks 😄

**Comment by lukelast** [comment]
While trying to do that I discovered the issue is only reproducible if the class is generated by an annotation processor, so I created a new `async-with-anotation-processor` integration test.

Can you take a look?

https://github.com/lukelast/gwt-maven-plugin/tree/master/src/it/async-with-anotation-processor

**Comment by lukelast** [comment]
To summarize in case anyone else hits this rare issue, these are the required conditions.

- Use the `gwt:generateAsync` feature of the `gwt-maven-plugin`
- Use an annotation generator to create a class (like a DTO) and use that generated class in your `RemoteService` method.
- Import that class with a wildcard import statement in your `RemoteService` interface.

All 3 of those must be true to hit the issue.

**Comment by ibaca** [comment]
The problem is that you are generating the @GenDto to late. You need to disable the javac annotation processor and use the maven-processor-plugin instead. Also, this plugin should appear before the gwt-maven-plugin because both are executed in the same phase, so it's important that it appear in this order so gwt-maven-plugin will see the target/generated-sources/annotations as a project.compileSourceRoots.

So in your example a configuration like this in the build section will works
```xml
	<build>
		<finalName>hello</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
					<proc>none</proc>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>2.2.4</version>
				<executions>
					<execution>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/annotations</outputDirectory>
							<processors>
								<processor>com.gwtplatform.dispatch.annotation.processor.GenDtoProcessor</processor>
							</processors>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.8.0-SNAPSHOT</version>
				<configuration>
					<draftCompile>true</draftCompile>
				</configuration>
				<executions>
					<execution>
						<id>generateAsync</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generateAsync</goal>
						</goals>
					</execution>
					<execution>
						<id>compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

If the source root is not added correctly, the type just appear without package, described here https://github.com/paul-hammant/qdox#resolving-class-names. And this line https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/gwt/GenerateAsyncMojo.java#L357 should include the target/generated-sources/annotations, if is not included is because the files are been generated too late.
