### ISSUE TITLE
Resolving dependencies for gwt-dev and gwt-user doesn't factor in exclusions

### ISSUE THREAD

**Issue by csadilek** [gwt-maven-plugin/gwt-maven-plugin#136]
When the plugin resolves dependencies for gwt-dev and gwt-user it doesn't take into account possible dependency exclusions. This is important as in GWT 2.8.0-rc1 lots of dependencies have been unbundled from gwt-dev and are now brought it using maven dependency resolution instead [1][2]. This gives users more control over their classpath, but only if the plugin respects possible exclusions (i.e. we don't want the apache-jsp dependency from jetty on the classpath as it breaks SDM on other containers).

The problematic code seems to be in [3]. @ibaca We (@mbarkley and I) will try and work on a fix for this and send a PR later today, if you're OK with this. I think this would be a great addition before the rc1 release.

[1] https://github.com/gwtproject/gwt/commit/9252212887f6991b0ef08d40352bede7d96a37a9
[2]  https://github.com/gwtproject/gwt/commit/b4b8e7c56210bf49e676f713c4f999a4fd8e0b0d
[3] https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/gwt/AbstractGwtMojo.java#L275

**Comment by ibaca** [comment]
I'm ok with fixing this plugin to make it work with 2.8.0-rc1, but... not sure if this can be used just as an excuse to not migrate to the new generation plugin https://github.com/tbroyer/gwt-maven-plugin, which was rewrited because of this explicit dependencies problem and other multi-module project configuration that really cannot (or do not worth) to apply to this plugin. Maybe we can dedicate our efforts improving the migration  guide (https://tbroyer.github.io/gwt-maven-plugin/migrating.html) instead of facilitates the usage of this plugin, what do you think? Why aren't you using the new plugin?

**Comment by csadilek** [comment]
@ibaca agreed, we will switch to the new plugin, we just have some branches of our product where we can't switch right now (not until the next/next release) :(.

**Comment by ibaca** [comment]
Fixed by https://github.com/gwt-maven-plugin/gwt-maven-plugin/pull/138

Thanks @mbarkley and @csadilek!

One question, I'm thinking in making some pull request to update the errai archetypes so it use the new gwt-maven-plugin, is this the right repo to make this pull request https://github.com/csadilek/archetypes/?

**Comment by mbarkley** [comment]
@ibaca We haven't maintained the archetypes in some time. We usually recommend users start by cloning [this tutorial](https://github.com/errai/errai-tutorial).
